const WORDS = new Set([
  "makan","minum","tidur","bangun","berjalan","berlari","duduk","berdiri",
  "membaca","menulis","mendengar","melihat","bicara","berbicara","berkata",
  "pergi","datang","pulang","masuk","keluar","naik","turun","terbang",
  "berenang","menari","bernyanyi","bermain","bekerja","belajar","mengajar",
  "membeli","menjual","membawa","mengambil","memberikan","menerima",
  "membuka","menutup","memotong","memasak","mencuci","menyapu","mengepel",
  "menyiram","menanam","memanen","menggambar","melukis","membangun",
  "merusak","memperbaiki","mencari","menemukan","kehilangan","memilih",
  "membuang","menyimpan","mengingat","melupakan","mengerti","memahami",
  "mengetahui","bertanya","menjawab","menjelaskan","menunggu","berharap",
  "bermimpi","tertawa","menangis","tersenyum","mencintai","membenci",
  "merindukan","mengunjungi","meninggalkan","mendorong","menarik",
  "mengangkat","menjatuhkan","melempar","menangkap","memukul","menendang",
  "melompat","merangkak","berputar","berhenti","mulai","selesai",
  "menyelesaikan","mengerjakan","melakukan","membuat","menciptakan",
  "menghancurkan","menghapus","menambah","mengurangi","menghitung",
  "mengisi","mengosongkan","menyalakan","mematikan","mengikat","melepas",
  "memasang","melepaskan","mengirim","membalas","menelepon","mengetik",
  "mencetak","menyalin","menggunting","menjahit","menggoreng","merebus",
  "mengaduk","mencampur","menuang","menyaring","menabrak","menghindari",
  "mengejar","bersembunyi","mengawasi","menjaga","melindungi","menyerang",
  "bertahan","menyerah","bertanding","berlomba","berlatih",
  "kepala","rambut","dahi","mata","hidung","telinga","mulut","bibir",
  "gigi","lidah","dagu","pipi","leher","bahu","dada","perut",
  "punggung","pinggang","lengan","siku","tangan","jari","kuku",
  "paha","lutut","betis","kaki","tumit","telapak","tulang","otot",
  "kulit","darah","jantung","otak","hati","ginjal","lambung",
  "kucing","anjing","burung","ikan","sapi","kambing","domba","kuda",
  "gajah","singa","harimau","beruang","serigala","rubah","rusa",
  "kelinci","tikus","monyet","gorila","ular","buaya","kadal",
  "katak","kodok","penyu","paus","hiu","gurita","kepiting","udang",
  "kerang","siput","lebah","semut","lalat","nyamuk","kecoak",
  "elang","gagak","merpati","ayam","bebek","angsa","merak",
  "bangau","penguin","kumbang","belalang","capung","jangkrik","cacing",
  "landak","musang","tupai","hamster","iguana",
  "nasi","roti","bakso","sate","soto","rendang","gudeg",
  "daging","telur","tempe","tahu","sayur","kangkung","bayam",
  "wortel","kentang","tomat","bawang","cabai","jahe","kunyit",
  "lada","garam","gula","kecap","sambal","kerupuk","keju",
  "mentega","susu","yogurt","cokelat","permen","kue","biskuit",
  "puding","selai","madu","apel","jeruk","pisang","mangga",
  "anggur","semangka","melon","pepaya","nanas","durian","rambutan",
  "manggis","salak","jambu","kelapa","alpukat","stroberi","lemon",
  "kopi","teh","sirup","soda","martabak","lumpia","donat",
  "pizza","burger","sup","bubur","lontong","ketupat","opor","rawon",
  "rumah","sekolah","kantor","toko","pasar","restoran","kafe",
  "hotel","bandara","stasiun","pelabuhan","terminal","apotek",
  "perpustakaan","museum","bioskop","stadion","taman","kebun",
  "sawah","ladang","hutan","gunung","pantai","pulau","danau",
  "sungai","laut","gua","lembah","bukit","padang","desa","kota",
  "negara","benua","masjid","gereja","istana","benteng","jembatan",
  "gedung","menara","penjara","asrama","villa","apartemen","gudang",
  "garasi","halaman","teras","balkon","kamar","dapur","toilet",
  "tangga","lorong","pintu","jendela","meja","kursi","lemari",
  "kasur","bantal","selimut","karpet","lampu","kipas","televisi",
  "radio","telepon","komputer","laptop","kamera","jam","cermin",
  "sisir","sikat","handuk","sabun","sampo","sendok","garpu",
  "pisau","piring","mangkok","gelas","cangkir","botol","teko",
  "wajan","panci","kulkas","ember","sapu","tas","dompet","kunci",
  "gembok","rantai","tali","benang","jarum","gunting","paku",
  "palu","obeng","gergaji","sekop","kapak","payung","tongkat",
  "kacamata","topi","helm","sepatu","sandal","kaos","kemeja",
  "celana","rok","jaket","dasi","sarung","syal","gelang",
  "kalung","cincin","anting","buku","pensil","pulpen","penghapus",
  "penggaris","kertas","lilin","pasir","batu","tanah","air",
  "awan","hujan","salju","kabut","petir","angin","badai",
  "pelangi","matahari","bulan","bintang","planet",
  "mobil","motor","sepeda","truk","taksi","kereta","kapal",
  "perahu","pesawat","helikopter","roket","ambulans","becak",
  "skuter","traktor","besar","kecil","panjang","pendek","tinggi",
  "rendah","lebar","sempit","tebal","tipis","berat","ringan",
  "keras","lembut","basah","kering","panas","dingin","hangat",
  "sejuk","gelap","terang","cerah","merah","kuning","hijau",
  "biru","ungu","coklat","hitam","putih","emas","perak","jingga",
  "cantik","tampan","lucu","imut","indah","bagus","buruk","baik",
  "jahat","pintar","rajin","malas","cepat","lambat","kuat","lemah",
  "berani","sabar","jujur","setia","ramah","sombong","sopan",
  "tenang","ramai","sepi","sibuk","santai","lapar","kenyang",
  "haus","lelah","segar","sehat","sakit","muda","baru","lama",
  "modern","mewah","mahal","murah","sulit","mudah","nyata",
  "asli","utuh","rusak","kotor","bersih","rapi","lengkap","penuh",
  "gokil","mantap","keren","seru","gabut","santuy","cuan",
  "bucin","baper","ambyar","ngopi","nongkrong","ngobrol","ngemil",
  "nyasar","nyaman","jomblo","mager","rebahan","kepo","julid",
  "dunia","alam","langit","bumi","hidup","lahir","tumbuh",
  "perang","damai","cinta","kasih","sayang","rindu","mimpi",
  "harapan","tujuan","impian","keluarga","ayah","ibu","kakak",
  "adik","nenek","kakek","paman","bibi","sepupu","teman",
  "sahabat","musuh","tetangga","guru","murid","dokter","polisi",
  "tentara","pilot","petani","nelayan","pedagang","karyawan",
  "presiden","menteri","gubernur","hakim","pengacara","insinyur",
  "arsitek","seniman","penulis","wartawan","fotografer","musisi",
  "penyanyi","aktor","sutradara","atlet","pelatih","wasit","pemain",
  "internet","aplikasi","digital","online","streaming","viral",
  "konten","media","platform","server","browser","password","email",
  "gaming","selfie","filter","podcast","startup","freelance",
  "vitamin","protein","mineral","vaksin","bakteri","virus","masker",
  "zona","zebra","zaman","wajib","wakil","warga","warna","warung",
  "wisata","wisuda","variasi","versi","video","visual","volume",
  "bahaya","bahagia","bahasa","bakat","bangga","bangkit","bangsa",
  "bantuan","batas","batik","bebas","bekal","belanja","benda",
  "bendera","bengkel","bentuk","berani","berita","berkat","berkah",
  "bersama","bisnis","bocah","bohong","bonus","budaya","bumbu",
  "bungkus","busuk","butuh","abadi","acara","adat","agenda",
  "akhir","akibat","aksi","aktif","alamat","album","alergi",
  "amunisi","antara","antusias","area","artikel","asuransi",
  "atmosfer","awal","balap","bandel","beban","bedah","belakang",
  "bijak","bimbang","brutal","cahaya","cakar","cakap","cakrawala",
  "campuran","candaan","cangkang","capek","catat","catur","cuaca",
  "curiga","daerah","dahsyat","dampak","dangkal","darurat","debat",
  "dekap","dekorasi","demonstrasi","dendang","dermaga","detik",
  "dialog","dimensi","dinamis","dinding","diploma","diskon",
  "distribusi","dongeng","drama","drastis","efek","efisien",
  "ekonomi","ekspedisi","eksperimen","ekspresi","elastis","elemen",
  "embun","emosi","energi","episode","evaluasi","evolusi",
  "fabrik","fakta","familiar","fantasi","favorit","festival",
  "figur","filosofi","fokus","formula","foto","fragmen","frustasi",
  "fungsi","galeri","gampang","gangguan","garuk","gelombang",
  "gempa","generasi","gerak","gerombolan","giat","global",
  "golongan","gosip","granat","gravitasi","gubuk","hadiah",
  "hambatan","hantam","harmoni","hebat","hemat","hiasan","hikayat",
  "hindari","hobi","hormat","ibadah","identitas","ikatan","iklan",
  "ilmu","ilustrasi","imbalan","impor","industri","informasi",
  "inisiatif","inovasi","inspirasi","instruksi","investigasi",
  "investasi","jadwal","jagoan","jaminan","jawaban","jejak",
  "jelajah","jempol","jenderal","jernih","jilid","juara","jumlah",
  "jurnal","justru","kabinet","kacau","kalender","kalimat",
  "kampanye","kandang","kapasitas","karakter","karier","karya",
  "katalog","kategori","keluhan","kemampuan","kemasan","kendaraan",
  "kenangan","kerajinan","kerangka","kerjasama","kesempatan",
  "ketua","kewajiban","khusus","klaim","klasik","klien","klinik",
  "koleksi","kombinasi","komedi","kompetisi","komunikasi","kondisi",
  "konflik","konstruksi","konsumen","kontrak","koordinasi","korupsi",
  "kreatif","kritik","kurikulum","kursus","kualitas","kuantitas"
]);

const LETTER_COMBOS = {
  easy: [
    "AN","IN","AR","AT","ER","AK","AL","AM","AS","UN","UK","US",
    "EN","EM","EL","RI","KA","MA","SA","TA","PA","LA","DA","RA",
    "BA","GA","HA","JA","WA","BI","DI","KI","MI","NI","PI","SI","TI"
  ],
  medium: [
    "ANG","ING","UNG","ANT","INT","AND","AMP","IMP",
    "KAN","MAN","TAN","PAN","BAN","RAN",
    "KER","BER","TER","PER","SER",
    "LAH","KAH","TAH","BAH","RAH",
    "BEL","GEL","SEL","TEL","KEL"
  ],
  hard: [
    "NGA","NJA","NCE","NTU","MPU","NDU",
    "STA","TRA","KRI","PRI","GRA","PRO","KRE",
    "NSI","RSI","NDA","MBA","RBA","RDA","RKA","RNA"
  ]
};

function getRandomLetters(round = 1) {
  let pool;
  if (round <= 3) pool = LETTER_COMBOS.easy;
  else if (round <= 8) pool = [...LETTER_COMBOS.easy, ...LETTER_COMBOS.medium];
  else pool = [...LETTER_COMBOS.easy, ...LETTER_COMBOS.medium, ...LETTER_COMBOS.hard];
  return pool[Math.floor(Math.random() * pool.length)];
}

function isValidWord(word) {
  return WORDS.has(word.toLowerCase().trim());
}

module.exports = { WORDS, getRandomLetters, isValidWord };
